Lesson12
Rkros34/Krivonos pull request #10
Opened 2022-07-05 15:00 UTC by Rkros34

2022-07-05 15:42 UTC, maximtereshchenko requested changes

2022-07-05 15:42 UTC, maximtereshchenko commented on src/main/java/by/it_academy/lesson12/Game.java
> +                String[] listOfGame=str.split("\\,");
наверное можно было просто str.split(",")

2022-07-05 15:42 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/Game.java
> +                new GameInfo(listOfGame[0],listOfGame[1], Integer.parseInt(listOfGame[2]),Integer.parseInt(listOfGame[3]));
наверное нужно созданные объекты складывать в список или как то так

2022-07-05 15:42 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/NumberInThirdPower.java
> +            } {
тут явно лишние скобочки, можно было просто 
numbers.add(Integer.valueOf(line));
System.out.println(line);
вместо 
{
numbers.add(Integer.valueOf(line));
System.out.println(line);
}

2022-07-05 15:42 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/NumberInThirdPower.java
> +                    double thirdPower = Math.pow(digit, 3);
можно было просто` digit*digit*digit`

2022-07-14 09:37 UTC, Xini1 requested changes
Не забывай про автоформатирование

2022-07-14 09:37 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/GameInfo.java
> +        return "dead heat";
В случае ничьи вернётся dead heat получается?)

2022-07-14 09:37 UTC, Xini1 commented on src/main/java/by/it_academy/lesson12/Game.java
> +        var teamFromUser = scanner.nextLine();
Надеюсь, что ты не совсем бездумно var вставляешь. Мы такое на курсах не рассматриваем

2022-07-17 12:34 UTC, Rkros34 commented on src/main/java/by/it_academy/lesson12/Game.java
> +        var teamFromUser = scanner.nextLine();
мне кажется это на лекции было по этой теме, var ставили, когда был очевиден тип переменной.

2022-07-17 12:36 UTC, Rkros34 commented on src/main/java/by/it_academy/lesson12/GameInfo.java
> +        return "dead heat";
изначально хотел так, но потом посмотрел, что в файле нет случаев ничьей и уже дальше не проверял. Наверное не будет работать дальше.

2022-07-29 15:45 UTC, merged